export type GeneratedFile = {
  path: string;
  content: string;
};

export type GeneratedProject = {
  slug: string;
  title: string;
  files: GeneratedFile[];
};

export function isWebsiteBuildPrompt(prompt: string) {
  const lower = prompt.toLowerCase();
  return (
    /\b(build|create|make|generate|design)\b/.test(lower) &&
    /\b(website|site|landing page|web page|homepage|portfolio)\b/.test(lower)
  );
}

export function generateWebsiteProject(prompt: string): GeneratedProject {
  const title = inferTitle(prompt);
  const slug = slugify(title);
  const audience = inferAudience(prompt);
  const palette = inferPalette(prompt);

  return {
    slug,
    title,
    files: [
      {
        path: "index.html",
        content: html(title, audience),
      },
      {
        path: "styles.css",
        content: css(palette),
      },
      {
        path: "script.js",
        content: js(title),
      },
      {
        path: "README.md",
        content: readme(title, prompt),
      },
    ],
  };
}

function inferTitle(prompt: string) {
  const quoted = prompt.match(/["']([^"']{3,80})["']/)?.[1];
  if (quoted) return titleCase(quoted);

  const forMatch = prompt.match(/\bfor\s+([a-z0-9\s&'-]{3,60})/i)?.[1];
  if (forMatch) return titleCase(forMatch.replace(/\b(website|site|landing page)\b/gi, "").trim());

  if (prompt.toLowerCase().includes("portfolio")) return "Signal Portfolio";
  if (prompt.toLowerCase().includes("restaurant")) return "Tableline";
  if (prompt.toLowerCase().includes("agency")) return "Launchgrid";
  return "Magi Site";
}

function inferAudience(prompt: string) {
  const lower = prompt.toLowerCase();
  if (lower.includes("restaurant")) return "guests ready to book a table";
  if (lower.includes("portfolio")) return "clients reviewing your work";
  if (lower.includes("saas") || lower.includes("startup")) return "teams comparing serious tools";
  if (lower.includes("detailing") || lower.includes("car")) return "drivers who want premium service";
  return "visitors who need a clear reason to act";
}

function inferPalette(prompt: string) {
  const lower = prompt.toLowerCase();
  if (lower.includes("luxury")) return { bg: "#090807", ink: "#f7efe2", accent: "#c9a45d", alt: "#1d1712" };
  if (lower.includes("tech") || lower.includes("saas")) return { bg: "#071015", ink: "#eef8fb", accent: "#4fd1c5", alt: "#10212a" };
  if (lower.includes("clean") || lower.includes("medical")) return { bg: "#f7fbfa", ink: "#10201d", accent: "#0f8b8d", alt: "#e7f2ef" };
  return { bg: "#111111", ink: "#f4efe6", accent: "#e63b35", alt: "#1c1c1c" };
}

function html(title: string, audience: string) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)}</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <header class="nav">
      <strong>${escapeHtml(title)}</strong>
      <nav>
        <a href="#services">Services</a>
        <a href="#proof">Proof</a>
        <a href="#contact">Contact</a>
      </nav>
    </header>

    <main>
      <section class="hero">
        <p class="eyebrow">Built for ${escapeHtml(audience)}</p>
        <h1>${escapeHtml(title)} turns attention into action.</h1>
        <p class="lede">
          A focused, high-converting website starter generated by MAGI. Replace the copy,
          add real imagery, and launch the first version fast.
        </p>
        <div class="actions">
          <a class="button" href="#contact">Start now</a>
          <a class="button secondary" href="#services">See services</a>
        </div>
      </section>

      <section class="band" id="services">
        <h2>What visitors can do</h2>
        <div class="grid">
          <article>
            <span>01</span>
            <h3>Understand the offer</h3>
            <p>Sharp positioning and simple sections make the value obvious in seconds.</p>
          </article>
          <article>
            <span>02</span>
            <h3>Trust the proof</h3>
            <p>Use this area for testimonials, metrics, before-and-after work, or case studies.</p>
          </article>
          <article>
            <span>03</span>
            <h3>Take the next step</h3>
            <p>Every section routes users toward a clear contact or checkout action.</p>
          </article>
        </div>
      </section>

      <section class="proof" id="proof">
        <h2>Ready for real content</h2>
        <p>
          Swap in your photos, customer quotes, pricing, and booking links. The layout is
          intentionally compact so it can become a real first launch instead of a mockup.
        </p>
      </section>

      <section class="contact" id="contact">
        <h2>Make contact easy</h2>
        <form>
          <input placeholder="Name" />
          <input placeholder="Email" type="email" />
          <textarea placeholder="What do you need?"></textarea>
          <button type="button">Send request</button>
        </form>
      </section>
    </main>

    <script src="script.js"></script>
  </body>
</html>
`;
}

function css(palette: { bg: string; ink: string; accent: string; alt: string }) {
  return `:root {
  --bg: ${palette.bg};
  --ink: ${palette.ink};
  --accent: ${palette.accent};
  --alt: ${palette.alt};
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--ink);
}

a { color: inherit; }
.nav {
  position: sticky;
  top: 0;
  z-index: 5;
  display: flex;
  justify-content: space-between;
  gap: 24px;
  padding: 18px clamp(18px, 4vw, 56px);
  border-bottom: 1px solid color-mix(in srgb, var(--ink), transparent 82%);
  background: color-mix(in srgb, var(--bg), transparent 8%);
  backdrop-filter: blur(16px);
}
.nav nav {
  display: flex;
  gap: 18px;
  color: color-mix(in srgb, var(--ink), transparent 24%);
}
.nav a { text-decoration: none; }

.hero {
  min-height: 78vh;
  display: grid;
  align-content: center;
  padding: clamp(56px, 9vw, 120px) clamp(18px, 7vw, 96px);
  background:
    linear-gradient(120deg, color-mix(in srgb, var(--accent), transparent 70%), transparent 42%),
    radial-gradient(circle at 78% 22%, color-mix(in srgb, var(--accent), transparent 68%), transparent 28%);
}
.eyebrow {
  color: var(--accent);
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}
h1 {
  max-width: 880px;
  margin: 0;
  font-size: clamp(3rem, 9vw, 7.5rem);
  line-height: 0.92;
  letter-spacing: 0;
}
.lede {
  max-width: 660px;
  margin: 26px 0 0;
  color: color-mix(in srgb, var(--ink), transparent 22%);
  font-size: 1.12rem;
  line-height: 1.7;
}
.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 32px;
}
.button,
button {
  border: 0;
  background: var(--accent);
  color: var(--bg);
  padding: 13px 18px;
  font-weight: 800;
  text-decoration: none;
  cursor: pointer;
}
.button.secondary {
  background: transparent;
  color: var(--ink);
  border: 1px solid color-mix(in srgb, var(--ink), transparent 72%);
}
.band,
.proof,
.contact {
  padding: clamp(48px, 7vw, 90px) clamp(18px, 7vw, 96px);
}
.band { background: var(--alt); }
h2 {
  max-width: 760px;
  margin: 0 0 24px;
  font-size: clamp(2rem, 5vw, 4.5rem);
  line-height: 1;
}
.grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
}
article {
  border: 1px solid color-mix(in srgb, var(--ink), transparent 82%);
  padding: 22px;
}
article span {
  color: var(--accent);
  font-weight: 900;
}
article p,
.proof p {
  color: color-mix(in srgb, var(--ink), transparent 24%);
  line-height: 1.65;
}
form {
  display: grid;
  max-width: 680px;
  gap: 12px;
}
input,
textarea {
  width: 100%;
  border: 1px solid color-mix(in srgb, var(--ink), transparent 76%);
  background: transparent;
  color: var(--ink);
  padding: 14px;
  font: inherit;
}
textarea { min-height: 130px; resize: vertical; }

@media (max-width: 760px) {
  .nav,
  .grid { grid-template-columns: 1fr; }
  .nav { display: grid; }
  .grid { display: grid; }
}
`;
}

function js(title: string) {
  return `document.querySelector("form button")?.addEventListener("click", () => {
  alert("${escapeJs(title)} request captured. Connect this form to your backend next.");
});
`;
}

function readme(title: string, prompt: string) {
  return `# ${title}

Generated by MAGI.

## Original Prompt

${prompt}

## Run

Open \`index.html\` in a browser.

## Files

- \`index.html\`
- \`styles.css\`
- \`script.js\`
`;
}

function slugify(value: string) {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 48) || "magi-site"
  );
}

function titleCase(value: string) {
  return value
    .split(/\s+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(" ");
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function escapeJs(value: string) {
  return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}
