import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — MAGI",
  description: "The terms governing use of MAGI.",
};

export default function Terms() {
  return (
    <main className="lp legal">
      <nav className="lp-nav">
        <Link href="/" className="lp-mark">MAGI</Link>
        <span className="lp-tag">Terms</span>
      </nav>

      <article className="legal-body">
        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: June 2026</p>

        <p className="legal-note">
          This is a starting template, not legal advice. Have a lawyer review it before relying on it.
        </p>

        <h2>1. What MAGI is</h2>
        <p>
          MAGI is an AI work engine that routes your request through multiple AI models to produce a
          written deliverable. By using MAGI you agree to these terms.
        </p>

        <h2>2. AI output is not guaranteed</h2>
        <p>
          MAGI&rsquo;s output is generated by AI and may contain errors, omissions, or out-of-date
          information, even when sources are cited. You are responsible for reviewing and verifying any
          output before relying on or acting on it. MAGI is not a substitute for professional (legal,
          financial, medical, or other) advice.
        </p>

        <h2>3. Acceptable use</h2>
        <p>
          Don&rsquo;t use MAGI to generate unlawful, harmful, infringing, or abusive content, to attempt
          to overload or reverse-engineer the service, or to violate the terms of the underlying model
          providers. We may suspend access for misuse.
        </p>

        <h2>4. Accounts &amp; billing</h2>
        <p>
          Paid plans, when available, are billed as described at checkout. Usage may be subject to fair-use
          and capacity limits. Fees are non-refundable except where required by law.
        </p>

        <h2>5. No warranty &amp; limitation of liability</h2>
        <p>
          MAGI is provided &ldquo;as is,&rdquo; without warranties of any kind. To the maximum extent
          permitted by law, we are not liable for any indirect, incidental, or consequential damages, or for
          decisions made based on MAGI&rsquo;s output.
        </p>

        <h2>6. Changes</h2>
        <p>We may update these terms; continued use after changes means you accept them.</p>

        <h2>7. Contact</h2>
        <p>Questions: samisosman52@gmail.com</p>

        <p className="legal-back"><Link href="/">← Back to MAGI</Link></p>
      </article>
    </main>
  );
}
