import { getModelPlan } from "@/lib/magi/model-plan";
import { generateText } from "@/lib/magi/providers";
import { classifyTask } from "@/lib/magi/task-router";
import type { GeminiModel, MagiArtifact, MagiMode, TaskProfile } from "@/lib/magi/types";
import type { GeneratedFile, GeneratedProject } from "@/lib/projects/website-generator";

export async function generateUniversalArtifactProject({
  prompt,
  mode,
  geminiModel,
  requestedType,
}: {
  prompt: string;
  mode: MagiMode;
  geminiModel?: GeminiModel;
  requestedType?: MagiArtifact["type"];
}): Promise<GeneratedProject> {
  const profile = classifyTask(prompt);
  const artifactType = requestedType || profile.artifactType;
  const plan = getModelPlan(mode, "balthasar", geminiModel);
  const system = [
    "You are MAGI's universal artifact builder.",
    "Create a complete, downloadable work product for the user's task.",
    "Return concise, concrete content. Do not write placeholder text.",
    "Preserve the user's intent and do not force a website/app framing unless the task route is website.",
    `Task route: ${JSON.stringify({ ...profile, artifactType }, null, 2)}`,
    `Judge rubric: ${profile.judgeRubric}`,
  ].join("\n");

  const response = await generateText({
    ...plan,
    system,
    prompt: `Create a downloadable ${artifactType} artifact package for this request:\n${prompt}`,
    maxTokens: 2400,
    temperature: 0.35,
  });

  const body = response.text.trim() || fallbackBody(profile, prompt);
  const files = filesForArtifact(profile, artifactType, prompt, body);
  const title = titleForArtifact(profile, prompt);

  return {
    title,
    slug: slugify(title),
    files,
  };
}

function filesForArtifact(
  profile: TaskProfile,
  artifactType: MagiArtifact["type"],
  prompt: string,
  body: string
): GeneratedFile[] {
  const readme = [
    `# ${titleForArtifact(profile, prompt)}`,
    "",
    "Generated by MAGI.",
    "",
    "## Original Prompt",
    "",
    prompt,
    "",
    "## Route",
    "",
    `- Task: ${profile.label}`,
    `- Artifact type: ${artifactType}`,
    `- Judge rubric: ${profile.judgeRubric}`,
    "",
  ].join("\n");

  if (artifactType === "code") {
    return [
      { path: "README.md", content: readme },
      { path: "IMPLEMENTATION.md", content: body },
      {
        path: "verification-checklist.md",
        content: [
          "# Verification Checklist",
          "",
          "- Inspect the target repo before applying changes.",
          "- Run the relevant formatter, typecheck, build, and tests.",
          "- Review the diff for unrelated churn.",
          "- Confirm secrets stay in environment variables.",
        ].join("\n"),
      },
    ];
  }

  if (artifactType === "data") {
    return [
      { path: "README.md", content: readme },
      { path: "analysis.md", content: body },
      {
        path: "schema-notes.json",
        content: JSON.stringify(
          {
            task: profile.kind,
            expectedInputs: ["CSV, spreadsheet, table, JSON, or pasted data"],
            checks: ["missing values", "types", "outliers", "calculation assumptions", "chart suitability"],
          },
          null,
          2
        ),
      },
    ];
  }

  const primaryName =
    artifactType === "report"
      ? "report.md"
      : artifactType === "plan"
        ? "plan.md"
        : artifactType === "document"
          ? "document.md"
          : "answer.md";

  return [
    { path: "README.md", content: readme },
    { path: primaryName, content: body },
    {
      path: "dossier.json",
      content: JSON.stringify(
        {
          taskKind: profile.kind,
          artifactType,
          skillPacks: profile.skillPacks,
          toolHints: profile.toolHints,
          judgeRubric: profile.judgeRubric,
        },
        null,
        2
      ),
    },
  ];
}

function fallbackBody(profile: TaskProfile, prompt: string) {
  return [
    `# ${profile.label}`,
    "",
    "MAGI could not get a live provider response for the artifact body, so it created this structured fallback.",
    "",
    "## Objective",
    "",
    prompt,
    "",
    "## Work Plan",
    "",
    "1. Clarify the concrete outcome.",
    "2. Gather the necessary inputs or files.",
    "3. Produce the smallest complete artifact.",
    "4. Verify against the route-specific rubric.",
    "5. Revise only the parts that fail verification.",
  ].join("\n");
}

function titleForArtifact(profile: TaskProfile, prompt: string) {
  const compact = prompt.replace(/\s+/g, " ").trim();
  return `${profile.label} Artifact - ${compact.slice(0, 42) || "MAGI Run"}`;
}

function slugify(value: string) {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 58) || "magi-artifact"
  );
}
